
@default-request = pokemon


### [request] pokemon
GET https://pokeapi.co/api/v2/pokemon/{{name}}

output pokemonId = {{OUT/id}}


### [request] encounters
@description = All encounters for specified pokémon
@method = GET
@host = https://pokeapi.co
@basePath = /api/v2
@endpoint = /pokemon/{{pokemonId}}/encounters


### [flow] pokemon-details: All previous steps

step -n pokemon
step -n encounters


### [request] dummy
GET https://pokeapi.co/api/v2/dummy

opt --mock

mock @responseFilePath = examples/data/encounters.response
mock Content-Type: application/json

output locationArea = {{OUT/[first].location_area}}
