
@default-request = pokemon


### [request] pokemon

@set-name = gengar

GET https://pokeapi.co/api/v2/pokemon/{{name}}

output pokemonId = {{OUT/id}}


### [request] encounters
@description = All encounters for specified pokémon
@method = GET
@host = https://pokeapi.co
@basePath = /api/v2
@endpoint = /pokemon/{{pokemonId}}/encounters


### [flow] pokemon-details: All previous steps

step -n pokemon
step -n encounters


### [request] dummy
POST https://pokeapi.co/api/v2/dummy

@list*-value = old-chateau-2f-right-room

opt --mock
mock @statusCode = 201
# mock @responseFilePath = examples/data/encounters.response
mock @responseContent = [{"location_area":{"name":"{{value}}"}}]
mock Content-Type: application/json

{
    "name": "ditto",
    "url": "https://pokeapi.co/api/v2/pokemon-species/132/"
}

output locationArea = {{OUT/[first].location_area}}
