
### [api]

Request-Catcher: {{request.catcher.identifier}}


### [request] authorization
POST http://localhost:{{local.server.port}}/oauth/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id={{clientId}}&client_secret={{clientSecret}}

output auth.bearer.token = {{OUT/access_token}}

assert EQUALS_TO 200 {{HTTP/status}}
