
### [api]
@protocol = http
@host = localhost
@port = {{local.server.port}}
@basePath = basic

auth @requestInputPath = src/test/resources/auth.spec.http
auth @inputName = authorization
auth @authType = TOKEN
auth @tokenParam = auth.bearer.token

opt -s clientId {{UUID:}}
opt -s clientSecret {{UUID:}}

Content-Type: application/json
Request-Catcher: {{request.catcher.identifier}}


### [request] create: Create with authorization
@method = POST
@endpoint = /body

{
    "access": "{{UUID:}}",
    "name": "{{FULL-NAME:}}",
    "email": "{{EMAIL:}}",
    "nickname": "{{ALPHA-NUMERIC:}}",
    "amount": {{DECIMAL:}},
    "active": {{BOOLEAN:}},
    "coins": {{INTEGER:}},
    "bio": "{{LOREM-IPSUM:}}",
    "type": "{{PICK-ANY:A,B,C}}",
    "timestamp": "{{DATE-TIME:}}"
}

output basic.functions.id = {{HTTP/header.Resource-ID}}

assert EQUALS_TO 201 {{HTTP/status}}


### [flow] createInFlow: Create with authorization within a flow

step -n create
