
### [api]

token @tokenUrl = http://localhost:{{local.server.port}}/oauth/token
token @clientId = {{UUID:}}
token @clientSecret = {{UUID:}}
token @scope = test
token @child_key = {{UUID:}}
token @child_secret = {{UUID:}}

opt -s clientId {{UUID:}}
opt -s clientSecret {{UUID:}}

Content-Type: application/json


### [request] create: Create with authorization
POST http://localhost:{{local.server.port}}/basic/body

{
    "access": "{{UUID:}}",
    "name": "{{FULL-NAME:}}",
    "email": "{{EMAIL:}}",
    "nickname": "{{ALPHA-NUMERIC:}}",
    "amount": {{DECIMAL:}},
    "active": {{BOOLEAN:}},
    "coins": {{INTEGER:}},
    "bio": "{{LOREM-IPSUM:}}",
    "type": "{{PICK-ANY:A,B,C}}",
    "timestamp": "{{DATE-TIME:}}"
}

output basic.functions.id = {{HTTP/header.Resource-ID}}

assert EQUALS_TO 201 {{HTTP/status}}


### [flow] createInFlow: Create with authorization within a flow

step -n create
