
### api:
@protocol = http
@domain = localhost
@port = {{local.server.port}}
@basePath = basic

Content-Type: application/json


### create
@method = POST
@endpoint = /body

{
    "access": "{{UUID:}}",
    "name": "{{FULL_NAME:}}",
    "email": "{{EMAIL:}}",
    "nickname": "{{ALPHA_NUMERIC:}}",
    "amount": {{DECIMAL:}},
    "active": {{BOOLEAN:}},
    "coins": {{INTEGER:}},
    "bio": "{{LOREM_IPSUM:}}",
    "type": "{{PICK_ANY:A,B,C}}",
    "timestamp": "{{DATE_TIME:}}"
}

// [output]
basic.functions.id = {{HTTP:header.Resource-ID}}

// [assertions]
EQUALS_TO! 201 {{HTTP:status}}


### obtain
@method = GET
@endpoint = /body/{{basic.functions.id}}

// [output]
basic.functions.entity = {{HTTP:response.path}}

// [assertions]
EQUALS_TO! 200 {{HTTP:status}}


### update
@method = PUT
@endpoint = /body/{{basic.functions.id}}
@bodyFilePath = {{basic.functions.entity}}

{
    "email": "jurl@test.com"
}

// [assertions]
EQUALS_TO! 204 {{HTTP:status}}


### remove
@method = DELETE
@endpoint = /body/{{basic.functions.id}}

// [assertions]
EQUALS_TO! 204 {{HTTP:status}}
