
### [api]
@protocol = http
@host = localhost
@port = {{local.server.port}}
@basePath = basic

Content-Type: application/json
Request-Catcher: {{request.catcher.identifier}}


### [request] create
@method = POST
@endpoint = /body
@bodyFilePath = src/test/resources/basic-functions.body.json

{
    "access": "{{UUID:}}",
    "name": "{{FULL_NAME:}}",
    "email": "{{EMAIL:}}",
    "nickname": "{{ALPHA_NUMERIC:}}",
    "amount": {{DECIMAL:}},
    "active": {{BOOLEAN:}},
    "coins": {{INTEGER:}},
    "bio": "{{LOREM_IPSUM:}}",
    "type": "{{PICK_ANY:A,B,C}}",
    "timestamp": "{{DATE_TIME:}}"
}

output basic.functions.id = {{HTTP/header.Resource-ID}}

assert EQUALS_TO 201 {{HTTP/status}}


### [request] obtain
@method = GET
@endpoint = /body/{{basic.functions.id}}

output basic.functions.entity = {{HTTP/response.path}}

assert EQUALS_TO 200 {{HTTP/status}}


### [request] update
@method = PUT
@endpoint = /body/{{basic.functions.id}}
@bodyFilePath = {{basic.functions.entity}}

{
    "email": "jurl@test.com"
}

assert EQUALS_TO 204 {{HTTP/status}}


### [request] remove
@method = DELETE
@endpoint = /body/{{basic.functions.id}}

assert EQUALS_TO 204 {{HTTP/status}}
