
source src/test/resources/auth.part.http

### [api]

Content-Type: application/json

@set-clientId = {{UUID:}}
@set-clientSecret = {{UUID:}}


### [request] create
POST http://localhost:{{local.server.port}}/basic/body

{
    "access": "{{UUID:}}",
    "name": "{{FULL_NAME:}}",
    "email": "{{EMAIL:}}",
    "nickname": "{{ALPHA_NUMERIC:}}",
    "amount": {{DECIMAL:}},
    "active": {{BOOLEAN:}},
    "coins": {{INTEGER:}},
    "bio": "{{LOREM_IPSUM:}}",
    "type": "{{PICK_ANY:A,B,C}}",
    "timestamp": "{{DATE_TIME:}}"
}

output basic.functions.id = {{HTTP/header.Resource-ID}}

assert EQUALS_TO 201 {{HTTP/status}}
