
### [api]
Content-Type: application/json


### [request] create
POST http://localhost:{{local.server.port}}/basic/body

@bodyFilePath = src/test/resources/basic-functions.body.json

{
    "access": "{{UUID:}}",
    "name": "{{FULL_NAME:}}",
    "email": "{{EMAIL:}}",
    "nickname": "{{ALPHA_NUMERIC:}}",
    "amount": {{DECIMAL:}},
    "active": {{BOOLEAN:}},
    "coins": {{INTEGER:}},
    "bio": "{{LOREM_IPSUM:}}",
    "type": "{{PICK_ANY:A,B,C}}",
    "timestamp": "{{DATE_TIME:}}"
}

output basic.functions.id = {{HTTP/header.Resource-ID}}

assert EQUALS_TO 201 {{HTTP/status}}


### [request] obtain
GET http://localhost:{{local.server.port}}/basic/body/{{basic.functions.id}}

output basic.functions.entity = {{HTTP/response.path}}

assert EQUALS_TO 200 {{HTTP/status}}


### [request] update
PUT http://localhost:{{local.server.port}}/basic/body/{{basic.functions.id}}
@bodyMergePath = {{basic.functions.entity}}
@bodyMergeAsBase = true

{
    "email": "jurl@test.com"
}

assert EQUALS_TO 204 {{HTTP/status}}


### [request] remove
DELETE http://localhost:{{local.server.port}}/basic/body/{{basic.functions.id}}

assert EQUALS_TO 204 {{HTTP/status}}
