
### [request] upload
http://localhost:{{local.server.port}}/file

file @path = src/test/resources/file.csv
file @field = This will be overrided because of @path appears twice

file @path = src/test/resources/file.csv
file @field = file
file @name = uploaded.csv
file @mineType = text/csv

form identifier = {{UUID:}}
form timestamp = {{DATE_TIME:}}

assert EQUALS_TO 201 {{HTTP/status}}


### [request] uploadWithoutForm
http://localhost:{{local.server.port}}/file

file @path = src/test/resources/file.csv
file @field = file

assert EQUALS_TO 201 {{HTTP/status}}


### [request] download
GET http://localhost:{{local.server.port}}/file
&file=src/test/resources/file.csv
&name=downloaded.csv

assert EQUALS_TO 200 {{HTTP/status}}


### [request] downloadWithoutName
GET http://localhost:{{local.server.port}}/file?
&file=src/test/resources/file.csv

assert EQUALS_TO 200 {{HTTP/status}}


### [request] downloadInLocation
GET http://localhost:{{local.server.port}}/file?
&file=src/test/resources/file.csv
&name=saved.csv

assert EQUALS_TO 200 {{HTTP/status}}


### [request] uploadFiles
http://localhost:{{local.server.port}}/file/set

file @path = src/test/resources/file-1.csv
file @field = files

file @path = src/test/resources/file-2.csv
file @field = files

file @path = src/test/resources/file-3.csv
file @field = files

assert EQUALS_TO 201 {{HTTP/status}}


### [request] uploadFileNotFound
http://localhost:{{local.server.port}}/file/set

file @path = src/test/resources/not-found.csv
file @field = files
