
### upload
http://localhost:{{local.server.port}}/file

file @name = uploaded.csv
file @path = src/test/resources/file.csv
file @field = file
file @mineType = text/csv

file identifier = {{UUID:}}
file timestamp = {{DATE_TIME:}}

assert EQUALS_TO 201 {{HTTP:status}}


### uploadWithoutForm
http://localhost:{{local.server.port}}/file

file @path = src/test/resources/file.csv
file @field = file

assert EQUALS_TO 201 {{HTTP:status}}


### download
GET http://localhost:{{local.server.port}}/file
file=src/test/resources/file.csv
&name=downloaded.csv

assert EQUALS_TO 200 {{HTTP:status}}


### downloadWithoutName
GET http://localhost:{{local.server.port}}/file?
file=src/test/resources/file.csv

assert EQUALS_TO 200 {{HTTP:status}}
