
### [api]

token @tokenUrl = http://localhost:{{local.server.port}}/oauth/token
token @clientId = {{UUID:}}
token @clientSecret = {{UUID:}}
token @scope = test


### [flow] basicWithAuthorization

@set-spec.path = {{workspacePath}}/src/test/resources

step -s flow.tag {{basic.with.authorization.tag}} -n create {{spec.path}}/basic-functions.spec.http
step -s flow.tag {{basic.with.authorization.tag}} -n obtain {{spec.path}}/basic-functions.spec.http
step -s flow.tag {{basic.with.authorization.tag}} -n update -mb json {{spec.path}}/basic-functions.spec.http
step -s flow.tag {{basic.with.authorization.tag}} -n remove {{spec.path}}/basic-functions.spec.http


### [flow] basicCrud

step -n create src/test/resources/basic-functions.spec.http
step -n obtain src/test/resources/basic-functions.spec.http
step -n remove src/test/resources/basic-functions.spec.http


### [flow] basicCrudDescription: Basic CRUD with description

step -n create src/test/resources/basic-functions.spec.http
step -n obtain src/test/resources/basic-functions.spec.http
step -n remove src/test/resources/basic-functions.spec.http


### [flow] basicWithQuery

@set-spec.path = {{workspacePath}}/src/test/resources

# First time this fails since 'basic.functions.id' has no value, it is set after 'create' step
step -s flow.tag {{basic.with.authorization.tag}} -n obtain {{spec.path}}/basic-functions.spec.http
step -s flow.tag {{basic.with.authorization.tag}} -n create {{spec.path}}/basic-functions.spec.http
step -s flow.tag {{basic.with.authorization.tag}} -n obtain {{spec.path}}/basic-functions.spec.http
step -s flow.tag {{basic.with.authorization.tag}} -n update -mb json {{spec.path}}/basic-functions.spec.http
step -s flow.tag {{basic.with.authorization.tag}} -n remove {{spec.path}}/basic-functions.spec.http


### [flow] invalidRecursiveFlow

step -n invalidRecursiveFlow src/test/resources/flow.spec.http


### [flow] noSteps


### [flow] errorOnStep

step -t five


### [flow] levels

step -n basicCrud


### [flow] basicCrudTwice

step -t 2 -n create src/test/resources/basic-functions.spec.http
step -t 2 -n obtain src/test/resources/basic-functions.spec.http
step -t 2 -n remove src/test/resources/basic-functions.spec.http
