
### [api]

Content-Type: application/json


### [request] obtain
GET http://localhost:{{local.server.port}}/basic/body/{{UUID:}}

mock @responseFilePath = src/test/resources/mock-response.output.json
mock @statusCode = 200

mock Identifier: {{UUID:}}

assert EQUALS_TO 200 {{HTTP/status}}
