
### [api]

token @tokenUrl = http://localhost:{{local.server.port}}/oauth/token
token @clientId = {{UUID:}}
token @clientSecret = {{UUID:}}
token @scope = test

Content-Type: application/json


### [request] create
POST http://localhost:{{local.server.port}}/basic/body

opt -ni

{
    "access": "{{UUID:}}",
    "name": "{{FULL-NAME:}}",
    "email": "{{EMAIL:}}",
    "nickname": "{{ALPHA-NUMERIC:}}",
    "amount": {{DECIMAL:}},
    "active": {{BOOLEAN:}},
    "coins": {{INTEGER:}},
    "bio": "{{LOREM-IPSUM:}}",
    "type": "{{PICK-ANY:A,B,C}}",
    "timestamp": "{{DATE-TIME:}}"
}

output basic.functions.id = {{HTTP/header.Resource-ID}}

assert EQUALS_TO 201 {{HTTP/status}}


### [request] skipped-auth-by-opt
POST http://localhost:{{local.server.port}}/basic/body

{
    "access": "{{UUID:}}",
    "name": "{{FULL-NAME:}}",
    "email": "{{EMAIL:}}",
    "nickname": "{{ALPHA-NUMERIC:}}",
    "amount": {{DECIMAL:}},
    "active": {{BOOLEAN:}},
    "coins": {{INTEGER:}},
    "bio": "{{LOREM-IPSUM:}}",
    "type": "{{PICK-ANY:A,B,C}}",
    "timestamp": "{{DATE-TIME:}}"
}

opt -na
