
source src/test/resources/parser/http-request.part.http

@default-request=request

### [request] request

mock @statusCode = 201
mock @responseContent = {}
mock Accept: application/json
mock field = discarded

auth @authType = TOKEN
auth @tokenParam = auth.bearer.token
auth field = discarded

file @mineType = text/csv
file identifier = {{UUID:}}

opt -s var1 value
opt -s var2 "string v a l u e"

# This is a comment
condition EQUALS_TO 1 1

POST http://localhost:5555/spec
&param=value

Content-Type: application/json

{
    "name": "test"
}

output basic.functions.id = {{HTTP/header.Resource-ID}}

assert EQUALS_TO 201 {{HTTP/status}}
assert com.legadi.cli.jurl.assertions.EqualsToAssertionFunction 201 {{HTTP/status}}
