source src/test/resources/parser/http-request.part.http

@default-request=

### [request] request

mock @statusCode = 201
mock @responseContent = {}
mock Accept: application/json

file @mineType = text/csv
file identifier = {{UUID:}}

# This is a comment
Content-Type: application/json

output basic.functions.id = {{HTTP/header.Resource-ID}}

assert EQUALS_TO 201 {{HTTP/status}}

### [flow] flow

step -s field value
# This is a comment
