
### [request] request

POST http://localhost:5555/spec

:test
Discarded-Header: discarded;

:all
Content-Type: application/txt

:default,  ,dev ,qa ,stage
Composing request with envs
{{ESCAPED:colon}} This is a normal line
:d.*
Env labeled with regex
{{EMPTY:}}
:label-.*
Discarded line
:default
EOF{{ESCAPED:lf}}